import { IPhoto } from "../admin/photo";
import { IUserPhone } from "../params/Admin/userPhone";
import { IUserProfession } from "../params/Admin/userProfession";
import { IUserQualification } from "../params/Admin/userQualification";
import { IUserAttachment } from "./userAttachment";
import { IUserExp } from "./userExp";


export interface ICandidate {
     //checked: boolean;
     id: number;
     applicationNo: number;
     gender: string;
     firstName: string;
     secondName: string;
     familyName: string;
     knownAs: string;
     referredBy?: number;
     referredByName: string;
     dOB?: Date;
     placeOfBirth: string;
     aadharNo: string;
     ppNo: string;
     ecnr: string;
     address: string;
     city: string;
     pin: string;
     district: string;
     nationality: string;
     email: string;
     companyId: number;
     created: Date;
     //introduction: string;
     //interests: string;
     appUserIdNotEnforced: string;
     appUserId: number;
     notificationDesired: boolean;
     candidateStatus?: number;     //EnumCnadidateStatus.NotReferred;
     photoUrl?: string;
     lastActive?: Date;
     userPhones: IUserPhone[];
     userQualifications: IUserQualification[];
     userProfessions: IUserProfession[];
     //userPassports: IUserPassport[];
     userAttachments: IUserAttachment[];
     //entityAddresses: IEntityAddress[];
     userExperiences: IUserExp[];
     userPhotos: IPhoto[];
     //userFormFiles: File[];
}

export class Candidate implements ICandidate {
     //checked: boolean;
     id= 0;
     applicationNo= 0;
     gender= '';
     firstName= '';
     secondName= '';
     familyName= '';
     knownAs= '';
     referredBy?= 0;
     referredByName= '';
     dOB?: Date;
     placeOfBirth= '';
     aadharNo= '';
     ppNo= '';
     ecnr='';
     address= '';
     city= '';
     pin= '';
     district= '';
     nationality= '';
     email= '';
     companyId= 0;
     created= new Date;
     //introduction= '';
     //interests= '';
     appUserIdNotEnforced= '';
     appUserId= 0;
     notificationDesired= false;
     candidateStatus?= 0;     //EnumCnadidateStatus.NotReferred;
     photoUrl?= '';
     lastActive?= new Date;
     userPhones: IUserPhone[]=[];
     userQualifications: IUserQualification[]=[];
     userProfessions: IUserProfession[]=[];
     //userPassports: IUserPassport[];
     userAttachments: IUserAttachment[]=[];
     //entityAddresses: IEntityAddress[];
     userExperiences: IUserExp[]=[];
     userPhotos: IPhoto[]=[];
     //userFormFiles: File[];
}